### ISSUE TITLE
Container conditions to skip tests?

### ISSUE THREAD

**Issue by juju4** [dev-sec/linux-baseline#102]
I'm start running puppet-os-hardening and testing inside travis and kitchen/docker.

I have tests failing while using base module without any customization while fully working on upstream (travis digitalocean or VM).
I fully expect some tests to fail inside docker because some sysctl are not allowed or systemd daemons start/stop/restart not working.

Is there a condition that can be added to skip test if inside docker?
like ansible virtualization fact

Looking at tests
(centos7) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/417935981
(bionic) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/417935982
(centos7) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/420516104#L2823
(bionic) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/420516105#L3408

Thanks

**Comment by artem-sidorenko** [comment]
@juju4 Thanks for this issue!

Baseline already has the container support, see this PR: https://github.com/dev-sec/linux-baseline/pull/91

Puppet-os-hardening implementation is pending, see this issue: https://github.com/dev-sec/puppet-os-hardening/issues/125

For the case you are looking for a reference, chef-os-hardening implementation was done in this PR: https://github.com/dev-sec/chef-os-hardening/pull/199

I hope this helps

**Comment by juju4** [comment]
ah that's great. I had not realized it was already as I saw some tests failing but was in other set of tests.
a pity not made to upstream inspec but will mimick this :)

Thanks a lot @artem-sidorenko!
