### ISSUE TITLE
/etc/passwd should not contain any password hashes

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/linux-baseline#117]
`/etc/shadow` exists already for a while and should always be used for password hashes instead of `/etc/passwd`. Due to legacy it's possible that a password hash will be still stored in `/etc/passwd`. Maybe we should have a test here for that.
(idea is based on the real incident)

**Comment by imjoseangel** [comment]
This can be easily managed. I will create a PR ASAP
