### ISSUE TITLE
net.ipv4.ip_forward needs to be '1' on docker hosts

### ISSUE THREAD

**Issue by krjensen** [dev-sec/linux-baseline#126]
Hi,

Running docker on a host, would need the net.ipv4.ip_forward to be '1' and that would make this test fail. Is there any way to work around that? I would really like a solution where I don't have to fork this module and maintain a copy my self. 

https://github.com/dev-sec/linux-baseline/blob/1233a136f319a3f2342c35ec06f325b1b0e94b36/controls/sysctl_spec.rb#L33

**Comment by chris-rock** [comment]
@krjensen you could easily contribute a new variable https://github.com/dev-sec/linux-baseline/blob/master/controls/sysctl_spec.rb#L343-L345. Otherwise InSpec offers an override mechanism where you could just overwrite specific controls to avoid the need of a fork.

**Comment by krjensen** [comment]
@chris-rock Than you for the feedback, I closed the issues because I found out that I could simply add it to an input-file and use `--input-file inspec/input.yml` as argument to inspec exec
