### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by micheelengronne** [dev-sec/linux-baseline#127]
Can you trigger a new release please ?

The current one is 6 months behind the master branch.

**Comment by chris-rock** [comment]
I'll take care of this asap

**Comment by chris-rock** [comment]
Fixed in https://github.com/dev-sec/linux-baseline/commit/cddd790870d3b868731a5e056d97275d96d04e6d

**Comment by micheelengronne** [comment]
Thanks.
