### ISSUE TITLE
Default umask 077/027 leads into several problems installing software packages

### ISSUE THREAD

**Issue by snoopotic** [dev-sec/linux-baseline#133]
https://github.com/dev-sec/linux-baseline/blob/85bc5a370972285670492361d3b56da6ecfd13e8/controls/os_spec.rb#L20

Hi,
may you explain what's the purpose for this default umask?
It lead me in problems especially installing python modules via pip after applying the ansible remediation role "dev-sec/os-hardening".
After installing them they are not usable by unprivileged users. Ubuntu has group "staff" set on /usr/local/lib/python3.8/dist-packages/ thus one way might be to add all users that are allowed to use that python modules to the "staff" group. Or - I change back the umask-default to usual 022.

What is your recommendation?

**Comment by rndmh3ro** [comment]
Hi Felix,

this is a CIS recommendation. Let me quote from there:

> Description: The default umask determines the permissions of files created by users. The user creating the file has the discretion of making their files and directories readable by others via the chmod command. Users who wish to allow their files and directories to be readable by others by default may choose a different default umask by inserting the umaskcommand into the standard shell configuration files ( .profile, .bashrc, etc.) in their home directories.

> Rationale: Setting a very secure default value for umask ensures that users make a conscious choice about their file permissions. A default umask setting of 077causes files and directories created by users to not be readable by any other user on the system. A umask of 027 would make files and directories readable by users in the same Unix group, while a umask of 022 would make files readable by every user on the system.

To your problem: 

> What is your recommendation?

You should never install python packages with pip globally. Install them with `--user` or use a virtualenv. Using pip globally breaks stuff.

When installing packages you could just run umask before the install command.

**Comment by snoopotic** [comment]
Well, thanks. The cited rationale  was what I assumed.
Well, this really enforces some more preliminary considerations in system design.

About the principle of unprivileged user installations...
It's a bit of that game "2 steps further and then one back" :D

**Comment by rndmh3ro** [comment]
> About the principle of unprivileged user installations...
It's a bit of that game "2 steps further and then one back" :D

Yeah, you're right. In production, use a virtualenv or a container. Never try to mess with the system python.
