### ISSUE TITLE
os-06: Check for SUID/ SGID blacklist control previously passing is now falling

### ISSUE THREAD

**Issue by se-dsingh** [dev-sec/linux-baseline#146]
**Describe the bug**
Control os-06 to check for the SUID/SGID blacklist, which was working as of 28 Jan 2021, is today no longer working due to changes in the control source code

**Expected behavior**
When running the inspec control via the inspec CLI, this control was previously found to be passing on the same version of the Ubuntu build.
```
19:31:59      amazon-ebs.<AMI_NAME>:   ✔  os-06: Check for SUID/ SGID blacklist
19:31:59      amazon-ebs.<AMI_NAME>:      ✔  suid_check diff should be empty
```

**Actual behavior**
Output seen now:
```
12:48:33      amazon-ebs.<AMI_NAME>:   ×  os-06: Check for SUID/ SGID blacklist
12:48:33      amazon-ebs.<AMI_NAME>:      ×  Control Source Code Error linux-baseline-master/controls/os_spec.rb:169
12:48:33      amazon-ebs.<AMI_NAME>:      wrong number of arguments (given 1, expected 0)
```

**Example code**
CLI Command to execute the profile:
```
inspec exec https://github.com/dev-sec/linux-baseline --backend ssh --host 127.0.0.1 --user worker --key-files /tmp/packer-provisioner-inspec.147623399.key --port 44157 --input-file /tmp/packer-provisioner-inspec.183185946.yml --no-distinct-exit --controls /os-(0[1-9]|1[0-1])(a|b)*$/ /package-(.*)$/ /sysctl-(.*)$/
```

**OS / Environment**
Ubuntu 18.04 AMD Server on AWS

**Inspec Version**
```
v4.26.4
```

**Baseline Version**
```
Version: 2.6.2
https://github.com/dev-sec/linux-baseline/commit/be16dbaa779fafda2ae7a5ef19e2b26abfc1dea8
```

**Additional context**
N/A

**Comment by schurzi** [comment]
sorry for the inconvenience. Please try again with current master. Everything should be fine again.

**Comment by se-dsingh** [comment]
Hi @schurzi thank you for the prompt response, I can confirm that it works. Closing this issue now.
