### ISSUE TITLE
why keep_logs?

### ISSUE THREAD

**Issue by snoopotic** [dev-sec/linux-baseline#171]
https://github.com/dev-sec/linux-baseline/blob/34b215b87cab41dd5fa7013ddfe7bd65b79d6e71/controls/package_spec.rb#L91

Hi. This default now caused me a many times a lot of research wondering why the auditd log folder/partition fills up and up and up... depending on the activity of the system you mostly find the issue very late or early.
Why do you recommend this setting as default and what is the purpose/idea behind? 
How to avoid an endless filling of this folder?
I'd say "rotate" is the better setting as default. 

Thanks

**Comment by schurzi** [comment]
In most cases we follow the general CIS Benchmark for Linux systems. This was implemented in PR https://github.com/dev-sec/linux-baseline/pull/85 to implement CIS DIL Benchmark 4.1.1.3.
Further information is available at https://www.cisecurity.org/benchmark/distribution_independent_linux
