### ISSUE TITLE
How to deal with squashfs in Ubuntu 22

### ISSUE THREAD

**Issue by schurzi** [dev-sec/linux-baseline#174]
https://github.com/dev-sec/linux-baseline/blob/07929ea2d1f64966d0ad8b29c7b9e6692b0d425a/controls/os_spec.rb#L257

I am currently trying to implement our hardening for Ubuntu 22. It turns out, that the included feature snap uses squashfs. I see two options for us:

* exclude squashfs from our baseline in Ubuntu 22
* advise to disable snap

What are your opinions?

**Comment by rndmh3ro** [comment]
A general rule is to remove/disable unused software. If snap is unused, it should be disabled/removed. Therefor squashfs then can be disabled.

So I'd say keep the control, but check if snap is used/installed. If it isn't, advice to disable squashfs:

```
    unless snap.exist?
      its(:content) { should match 'install squashfs /bin/true' }
    end
```

If we should advice to disable snap - I don't know.

**Comment by micheelengronne** [comment]
`snap` use in Ubuntu community is a very hot topic.

From ly understanding, Canonical is pushing so much for `snap` in Ubuntu it will become an intricated layer in the core, so I don't think we can currently advise on the use of `snap` or not.
