### ISSUE TITLE
Remove control 'os-08' because entropy is always at 256

### ISSUE THREAD

**Issue by andrejmaya** [dev-sec/linux-baseline#176]
**Is your feature request related to a problem? Please describe.**
inspec is failing at the `control 'os-08'` step on most of the newer kernels. This happened because of changes in newer Linux versions to RNG’s crypto and backports to older LTS Kernels. Basically, the entropy_avail number is now meaningless.

**Describe the solution you'd like**
Remove the control check os-08 here: https://github.com/dev-sec/linux-baseline/blob/master/controls/os_spec.rb#L230

**Describe alternatives you've considered**

**Additional context**
see here:
https://askubuntu.com/questions/1427470/entropy-is-stuck-at-256-after-upgrading-to-kernel-5-15-0-47

**Comment by rndmh3ro** [comment]
Sounds reasonable to me!
