### ISSUE TITLE
check for audit(d) fails on aws linux ami

### ISSUE THREAD

**Issue by kidbrax** [dev-sec/linux-baseline#60]
It seems a more robust check is need to include AWS linux.  For example this fails on Linux AMI evne though `audit ` is installed, https://github.com/dev-sec/linux-baseline/blob/58810fec3c4205f8e86daf8f92db698672340d9c/controls/package_spec.rb#L83

**Comment by artem-sidorenko** [comment]
@kidbrax Thanks for this issue! Its definitely makes sense. Can I maybe ask you to provide a PR on this?

**Comment by kidbrax** [comment]
Ok, turns out that it does seem to be detecting correctly but the auditd command is only available to root.  So it is a different issue.
