### ISSUE TITLE
package-08 error on amazon linux

### ISSUE THREAD

**Issue by larry-herz** [dev-sec/linux-baseline#79]
Amazon recently updated their platform_family from "rhel" to "amazon". With this change the package-08 control is now broken for amazon linux.

The package-08 control is set to look for an auditd package on all os flavors save for rhel and suse. 

Please add "amazon" to the list of os platforms to use the "audit" package.

**Comment by atomic111** [comment]
@larry-herz thanks for bringin this up. The pr #76 should solve your issue.

**Comment by atomic111** [comment]
@larry-herz i merge thr pr #76 . Can we close your issue?

**Comment by larry-herz** [comment]
Yes. That solved the issue. Thanks
