### ISSUE TITLE
Profile summary VS Test Summary 

### ISSUE THREAD

**Issue by wolfyy66** [dev-sec/linux-baseline#93]
Hi there, 

After launching the script/profile (how Am I supposed to call it ?)
I've the output that I was waiting for, the only thing that I couldn't understand is the difference between these two lines : 
![githubissue](https://user-images.githubusercontent.com/37833406/38862486-f693271e-422c-11e8-8eea-eacc16f26d98.PNG)

**Comment by chris-rock** [comment]
A control may include multiple test. In your case, the control `os-11` includes 3 tests

**Comment by wolfyy66** [comment]
I didn't quite understand
Do you mean that when I launch the execution, it runs 3 tests simultaneously ?

**Comment by rndmh3ro** [comment]
I guess you mean the Profile summary and the Test summary?

If yes, the profile has 25 controls. These 25 controls consist of 68 separate tests. So the profile "os-11" has 3 tests, as seen in the picture.

**Comment by szEvEz** [comment]
@wolfyy66 Was your question answered? :)

@rndmh3ro Can this issue be closed?

**Comment by rndmh3ro** [comment]
@wolfyy66 Feel free to reopen If the issue persists!
